AsciiComments:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
ClassLength:
  Max: 200
MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'Rakefile'
    - 'bin/rake'
    - 'vendor/**/*'
    - 'doc/**/*'
    - 'coverage/**/*'
    - 'tmp/**/*'
